graph TD
  commands
  engines
  foundations
  lib_collector_f6e3372d["lib-collector"]
  lib_render_e7a72dae["lib-render"]
  rust_arch_test_kit_35b16f27["rust-arch-test-kit"]
  commands --> engines
  commands --> foundations
  engines --> foundations
  engines --> rust_arch_test_kit_35b16f27
